<?php
/**
 * @copyright 2019 City of Bloomington, Indiana
 * @license https://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE
 */
declare (strict_types=1);
?>
<section>
    <div id="intro">
        <div>
            <p>Thank you for your interest in the Sidewalk Repair Assistance
               Program.  Once your application is reviewed a member of the
               Department of Public Works will contact you to discuss next steps
            </p>
        </div>
    </div>
</section>
