<header>
    <div class="menu-container">
        <a href="/" title="City of Bloomington" class="logo">
            <img src="/themes/contrib/cob/css/images/cob-logo-horizontal.svg" alt="City of Bloomington">
        </a>
        <a href="/" title="City of Bloomington, Indiana" class="name">Mayor Kerry Thomson</a>

        <div class="nav-items non-home">
            <form id="header-search" method="get" action="/search">
                <fieldset>
                    <label for="query" class="visually-hidden">Search</label>
                    <input id="query" name="query" type="search" class="form-search" title="Enter the terms you wish to search for." placeholder="Search the City of Bloomington" size="15" maxlength="128">
                    <input type="submit" class="button" value="Search">
                </fieldset>
            </form>
        </div>
    </div>

    <nav id="header-icon-nav">
        <div class="container">
            <a class="services" title="Top Services" href="/services">
                <span>Services</span>
                <span>Services</span>
            </a>

            <a class="info" title="Information &amp; Guides" href="/about">
                <span>Information</span>
                <span>Info</span>
            </a>

            <a class="news" title="News &amp; Events" href="/news">
                <span>News</span>
                <span>News</span>
            </a>

            <a class="meetings" title="News &amp; Events" href="/calendars">
                <span>Meetings &amp; Events</span>
                <span>Events</span>
            </a>

            <a class="city" title="City Government" href="/city">
                <span>City Government</span>
                <span>Govt.</span>
            </a>
        </div>
    </nav>
</header>
