<header>
    <div class="container">
        <section id="block-cob-branding">
            <h1><a href="/" title="Home" rel="home">City of Bloomington, Indiana</a></h1>
            <h2><a href="/" title="Home" rel="home">Mayor John Hamilton</a></h2>
        </section>
    </div>
</header>
<nav id="nav1">
    <div class="container">
        <a class="about"    href="/about">Information &amp; Guides</a>
        <a class="city"     href="/city">City Government</a>
        <a class="news"     href="/news">News &amp; Events</a>
        <a class="services" href="/services">Top Services</a>
    </div>
</nav>
