<header>
    <div class="container">
        <section id="block-cob-branding">
            <a href="/" title="City of Bloomington, Indiana - Home" rel="home">
                <h1>City of Bloomington, Indiana</h1>
                <h2>Mayor John Hamilton</h2>
            </a>
        </section>
    </div>
    <nav id="nav1">
        <div class="container">
            <a class="about"    href="/about">Information &amp; Guides</a>
            <a class="city"     href="/city">City Government</a>
            <a class="news"     href="/news">News &amp; Events</a>
            <a class="services" href="/services">Top Services</a>
        </div>
    </nav>
</header>
