---
- hosts: "sidewalk"
  become: "yes"
  roles:
    - "City-of-Bloomington.mysql"
    - "City-of-Bloomington.php"

  tasks:
    - name: "Install distro packages"
      apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
          - "php-mysql"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ sidewalk_db.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ sidewalk_db.user }}"
        password: "{{ sidewalk_db.pass }}"
        priv:     "{{ sidewalk_db.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
      with_items:
        - "{{ sidewalk_install_path }}"
        - "{{ sidewalk_backup_path  }}"
        - "{{ sidewalk_site_home    }}"

    - name: "Extract release"
      unarchive:
        src: "{{ sidewalk_archive_path }}"
        dest: "/usr/local/src"
      register: "release"

    - name: "Remove old release"
      file:
        path: "{{ sidewalk_install_path }}"
        state: "absent"
      when: "release.changed"

    - name: "Install release"
      command: "rsync -rlv /usr/local/src/sidewalk/ {{ sidewalk_install_path }}/"
      when: "release.changed"

    - name: "Update site_home"
      command: "rsync -rl /usr/local/src/sidewalk/data/ {{ sidewalk_site_home }}/"
      when: "release.changed"

    - name: "Update site_config"
      template:
        src: "site_config.j2"
        dest: "{{ sidewalk_site_home }}/site_config.inc"

    - name: "Apache site configuration"
      template:
        src: "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/sidewalk.conf"
      notify: "apache_restart"

    - name: "Update application permissions"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "www-data"
        group:   "staff"
        mode:    "g+rw"
        recurse: "yes"
      with_items:
        - "{{ sidewalk_install_path }}"
        - "{{ sidewalk_backup_path  }}"
        - "{{ sidewalk_site_home    }}"
...
