<p>This program is designed for targeted income areas within the city, as defined by
the Department of Housing and Urban Development’s CDBG designation. Funding is
prioritized for owner occupied, single-family properties that are within CDBG designated
areas. Any unclaimed funding that remains at the conclusion of this program will be
made available to single family, owner occupied, properties regardless of them being
located within a CDBG designated area. Additional funding will be distributed on a first
come, first serve basis for those interested property owners. Please contact the Public
Works Department at <a href="tel:+18123493410">(812) 349-3410</a> to place your name and
property on a waiting list.
</p>
